import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "assets_management": "Assets Management",
          "login": "Login",
          "please_sign_in_to_continue": "Please sign in to continue",
          "email": "Email",
          "enter_your_email": "Enter your email",
          "please_enter_your_email": "Please enter your email",
          "please_enter_valid_email": "Please enter valid email",
          "password": "Password",
          "enter_your_password": "Enter your password",
          "please_enter_password": "Please enter password",
          "strong_password":
              "ⓘ Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character.",
          "forgot_password_?": "Forgot password ?",
          "or_continue_with": "or continue with",
          "update_profile": "Update Profile",
          "price_per_unit": "Price Per Unit",
          "edit_asset": "Edit Asset",
          "don't_have_an_account_? ": "Don't have an account ? ",
          "sign_up": "Sign up",
          "create_account": "Create Account",
          "please_fill_the_input_below_here":
              "Please fill the input below here",
          "full_name": "Full Name",
          "enter_your_full_name": "Enter your full name",
          "please_enter_your_full_name": "Please enter your full name",
          "phone_no": "Phone No",
          "enter_your_phone_no": "Enter your phone no",
          "please_enter_your_phone_number": "Please enter your phone number",
          "confirm_password": "Confirm Password",
          "confirm_your_password": "Confirm your password",
          "please_confirm_your_password": "Please confirm your password",
          "ⓘ_password_incorrect._please_re-check_your_password.":
              "ⓘ Password incorrect. Please re-check your password.",
          "already_have_an_account_? ": "Already have an account ? ",
          "sign_in": "Sign in",
          "hello": "Hello ",
          "here_you_can_search_global_assets":
              "Here you can search global assets",
          "search_category": "Search Category",
          "news": "News",
          "view_all": "View All",
          "global": "Global",
          "setting": "Setting",
          "select_category": "Select Category",
          "you_can_select_any_category_in_which_you_are_interested":
              "You can select any category in which you are interested",
          "asset_name": "Asset Name",
          "asset_id": "Asset id",
          "number_of": "Number of",
          "asset_description": "Asset Description",
          "is_asset_solely_owned_?": "Is Asset solely owned ?",
          "%_owned": "% Owned",
          "name": "Name",
          "add_partners": "+ Add Partners",
          "save": "Save",
          "back": "Back",
          "current_news": "Current News",
          "read_more_at:": "Read more at:",
          "search_here...": "Search here...",
          "purchased": "Purchased",
          "current_market": "Current Market",
          "analyse": "Analyse",
          "asset_detail": "Asset Detail",
          "name:": "Name:",
          "location:": "Location:",
          "category:": "Category:",
          "sub_category:": "Sub Category:",
          "quantity:": "Quantity:",
          "description:": "Description:",
          "my_assets": "My Assets",
          "my_categories": "My Categories",
          "logout": "Logout",
        },
    'fr_FR': {
      "assets_management": "Gestion d'actifs",
      "login": "Se connecter",
      "please_sign_in_to_continue": "Veuillez vous connecter pour continuer",
      "email": "E-mail",
      "enter_your_email": "Entrer votre Email",
      "please_enter_your_email": "Veuillez entrer votre email",
      "please_enter_valid_email": "Veuillez entrer une adresse e-mail valide",
      "password": "Mot de passe",
      "enter_your_password": "Tapez votre mot de passe",
      "please_enter_password": "Veuillez entrer le mot de passe",
      "strong_password":
      "ⓘ Le mot de passe doit contenir au moins une lettre majuscule, une lettre minuscule, un chiffre et un caractère spécial.",
      "forgot_password_?": "Mot de passe oublié ?",
      "or_continue_with": "ou continuez avec",
      "update_profile": "Mettre à jour le profil",
        "price_per_unit": "Prix par unité",
      "edit_asset": "Modifier l'actif",
      "don't_have_an_account_? ": "Vous n'avez pas de compte ?",
      "sign_up": "S'inscrire",
      "create_account": "Créer un compte",
      "please_fill_the_input_below_here":
      "Veuillez remplir le champ ci-dessous ici",
      "full_name": "Nom et prénom",
      "enter_your_full_name": "Entrez votre nom complet",
      "please_enter_your_full_name": "S'il vous plait entrez votre nom entier",
      "phone_no": "Pas de téléphone",
      "enter_your_phone_no": "Entrez votre numéro de téléphone",
      "please_enter_your_phone_number": "Veuillez entrer votre numéro de téléphone",
      "confirm_password": "Confirmez le mot de passe",
      "confirm_your_password": "Confirmer votre mot de passe",
      "please_confirm_your_password": "Veuillez confirmer votre mot de passe",
      "ⓘ_password_incorrect._please_re-check_your_password.":
      "ⓘ Mot de passe incorrect. Veuillez revérifier votre mot de passe.",
      "already_have_an_account_? ": "Vous avez déjà un compte ?",
      "sign_in": "Se connecter",
      "hello": "Bonjour ",
      "here_you_can_search_global_assets":
      "Ici, vous pouvez rechercher des actifs mondiaux",
      "search_category": "Catégorie de recherche",
      "news": "Nouvelles",
      "view_all": "Voir tout",
      "global": "Mondiale",
      "setting": "Paramètre",
      "select_category": "Choisir une catégorie",
      "you_can_select_any_category_in_which_you_are_interested":
      "Vous pouvez sélectionner n'importe quelle catégorie qui vous intéresse",
      "asset_name": "Nom de l'actif",
      "asset_id": "Identifiant de l'actif",
      "number_of": "Nombre de",
      "asset_description": "Description de l'actif",
      "is_asset_solely_owned_?": "L'actif est-il la propriété exclusive ?",
      "%_owned": "% Possédée",
      "name": "Nom",
      "add_partners": "+ Ajouter des partenaires",
      "save": "Sauvegarder",
      "back": "Dos",
      "current_news": "Actualités actuelles",
      "read_more_at:": "Lire la suite sur:",
      "search_here...": "Cherche ici...",
      "purchased": "Achetée",
      "current_market": "Marché actuel",
      "analyse": "Analyser",
      "asset_detail": "Détail de l'actif",
      "name:": "Nom:",
      "location:": "Emplacement:",
      "category:": "Catégorie:",
      "sub_category:": "Sous-catégorie:",
      "quantity:": "Quantité:",
      "description:": "Description:",
      "my_assets": "Mes atouts",
      "my_categories": "Mes catégories",
      "logout": "Se déconnecter",
    },
      };
}
