import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "assets_management": "Assets Management",
          "login": "Login",
          "please_sign_in_to_continue": "Please sign in to continue",
          "email": "Email",
          "enter_your_email": "Enter your email",
          "please_enter_your_email": "Please enter your email",
          "please_enter_valid_email": "Please enter valid email",
          "password": "Password",
          "enter_your_password": "Enter your password",
          "please_enter_password": "Please enter password",
          "strong_password":
              "ⓘ Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character.",
          "forgot_password_?": "Forgot password ?",
          "or_continue_with": "or continue with",
          "update_profile": "Update Profile",
          "price_per_unit": "Price Per Unit",
          "don't_have_an_account_? ": "Don't have an account ? ",
          "sign_up": "Sign up",
          "create_account": "Create Account",
          "please_fill_the_input_below_here":
              "Please fill the input below here",
          "full_name": "Full Name",
          "enter_your_full_name": "Enter your full name",
          "please_enter_your_full_name": "Please enter your full name",
          "phone_no": "Phone No",
          "enter_your_phone_no": "Enter your phone no",
          "please_enter_your_phone_number": "Please enter your phone number",
          "confirm_password": "Confirm Password",
          "confirm_your_password": "Confirm your password",
          "please_confirm_your_password": "Please confirm your password",
          "ⓘ_password_incorrect._please_re-check_your_password.":
              "ⓘ Password incorrect. Please re-check your password.",
          "already_have_an_account_? ": "Already have an account ? ",
          "sign_in": "Sign in",
          "hello": "Hello ",
          "here_you_can_search_global_assets":
              "Here you can search global assets",
          "search_category": "Search Category",
          "news": "News",
          "view_all": "View All",
          "global": "Global",
          "setting": "Setting",
          "select_category": "Select Category",
          "you_can_select_any_category_in_which_you_are_interested":
              "You can select any category in which you are interested",
          "asset_name": "Asset Name",
          "asset_id": "Asset id",
          "number_of": "Number of",
          "asset_description": "Asset Description",
          "is_asset_solely_owned_?": "Is Asset solely owned ?",
          "%_owned": "% Owned",
          "name": "Name",
          "add_partners": "+ Add Partners",
          "save": "Save",
          "back": "Back",
          "current_news": "Current News",
          "read_more_at:": "Read more at:",
          "search_here...": "Search here...",
          "purchased": "Purchased",
          "current_market": "Current Market",
          "analyse": "Analyse",
          "asset_detail": "Asset Detail",
          "name:": "Name:",
          "location:": "Location:",
          "category:": "Category:",
          "sub_category:": "Sub Category:",
          "quantity:": "Quantity:",
          "description:": "Description:",
          "my_assets": "My Assets",
          "my_categories": "My Categories",
          "logout": "Logout",
        },
        'hi_IN': {},
      };
}
